name: Release Creation on Version Tag

on:
  repository_dispatch:
    types: [version-tagged]

# on:
#   push:
#     tags:
#       - "v*"
#   release:
#     types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # get part of the tag after the `v`
      # - name: Extract tag version number
      #   id: get_version
      #   uses: battila7/get-version-action@v2
      # - run: echo ${{ steps.get_version.outputs.version }}
      # - run: echo ${{ steps.get_version.outputs.version-without-v }}

      
      # Substitute the Manifest and Download URLs in the module.json
      - name: Substitute Manifest and Download Links For Versioned Ones
        id: sub_manifest_link_version
        uses: microsoft/variable-substitution@v1
        with:
          files: 'module.json'
        env:
          
          version: ${{github.event.client_payload.version}}
          url: https://github.com/${{github.repository}}
          manifest: https://github.com/${{github.repository}}/releases/latest/download/module.json
          download: https://github.com/${{github.repository}}/releases/download/${{github.event.client_payload.version}}/module.zip

      # Install packages.
      - run: npm install

      # Build distribution.
      - run: npm run build

      # Create a zip file with all files required by the module to add to the release.
      - run: zip -r ./module.zip module.json index.js index.js.map style.css assets/ dist/ lang/ packs/ LICENSE AUTHORS

      # Create a release for this specific version
      - name: Update Release with Files
        id: create_version_release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true # Set this to false if you want to prevent updating existing releases
          name: ${{github.event.client_payload.version}}
          # draft: ${{ github.event.release.draft }}
          # prerelease: ${{ github.event.release.prerelease }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: './module.json, ./module.zip'
          tag: ${{ github.event.client_payload.version }}
          body: ${{github.event.client_payload.version}}

